_wandb:
    value:
        cli_version: 0.22.2
        e:
            ctsthhc94u7l1daopfw6t9q91oe1kuz4:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1006321528832"
                        used: "480106889216"
                email: 142201019@smail.iitpkd.ac.in
                executable: c:\Users\sairo\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: f9a16ca3b18fcff9493a16ca880b4718898aa6d6
                    remote: https://github.com/sairohith24816/mlops2025w_142201019.git
                host: samsung
                memory:
                    total: "16837525504"
                os: Windows-10-10.0.26200-SP0
                program: <python with no main file>
                python: CPython 3.11.0
                root: c:\Users\sairo\Desktop\MLOps\mlops2025w_142201019\class\week-6
                startedAt: "2025-10-21T04:44:27.073191Z"
                writerId: ctsthhc94u7l1daopfw6t9q91oe1kuz4
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.11.0
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
